version: "3.9"
services:
  zmb_mongo:
    container_name: zmb_mongo
    image: mongo:6.0
    volumes:
      - /srv/host/zeromedomedia/mongo:/data/db
    networks:
      - zmb_data
    restart: unless-stopped

  zmb_api:
    container_name: zmb_api
    image: ghcr.io/tdjsnelling/sqtracker-api:latest
    volumes:
      - /srv/host/zeromedomedia/config/config.js:/sqtracker/config.js:ro
    depends_on:
      - zmb_mongo
    networks:
      - zmb_data
      - zmb_app_net
    restart: unless-stopped

  zmb_client:
    container_name: zmb_client
    image: ghcr.io/tdjsnelling/sqtracker-client:latest
    volumes:
      - /srv/host/zeromedomedia/config/config.js:/sqtracker/config.js:ro
    depends_on:
      - zmb_api
    networks:
      - zmb_app_net
      - nginx-expose
    restart: unless-stopped

networks:
  zmb_data:
    driver: bridge
  zmb_app_net:
    driver: bridge
  # Simple network with nginx container to expose web components
  nginx-expose:
    external: true
